const { runParserTests } = require('./unit/parser.test');
const { runEvaluatorTests } = require('./unit/evaluator.test');
const { runPipelineTests } = require('./integration/pipeline.test');
const { runMetamorphicTests } = require('./metamorphic/metamorphic.test');
const { runL4ClosureTests } = require('./regression/l4-closures.test');
const { runL4NegativeTests } = require('./regression/l4-negative.test');
const { runL4AuthenticityTests } = require('./regression/l4-authenticity.test');
const { runL4ResidualCorpusTests } = require('./regression/l4-residual-corpus.test');
const { runCorpusTests } = require('./corpus/corpus.test');
const { runMutationTests } = require('./mutation/mutation.test');
const { runFuzzTests } = require('./fuzz/fuzz.test');
const { runProtectedCorpusTests } = require('./regression/protected-corpus.test');
const { runRegressionTests } = require('./regression/root-fixture.test');
const { runMinimalGroundTruthTests } = require('./regression/minimal-ground-truth.test');
const { runL5AuthenticityNegativeTests } = require('./regression/l5-authenticity-negative.test');
const { runRound2AuthenticityTests } = require('./regression/round2-authenticity.test');
const { runRound3AuditTests } = require('./regression/round3-audit.test');
const { runSandboxTests } = require('./unit/sandbox.test');
const { runCliTests } = require('./unit/cli.test');
const { runAdmissionGateMatrixTests } = require('./unit/admission-gate-matrix.test');
const { runWorkerProtocolTests } = require('./unit/worker-protocol.test');
const { runQueueTests } = require('./unit/queue.test');
const { runGatewayTests } = require('./unit/gateway.test');
const { runPhase2SecurityTests } = require('./integration/phase2-security-e2e.test');
const { runRedisMultiProcessTests } = require('./integration/redis-multi-process-queue.test');
const { printSummary } = require('./test-framework');

console.log('====================================================');
console.log('         VALAX SOURCE RECOVERY TEST SUITE           ');
console.log('====================================================');

runParserTests();
runEvaluatorTests();
runPipelineTests();
runMetamorphicTests();
runL4ClosureTests();
runL4NegativeTests();
runL4AuthenticityTests();
runL4ResidualCorpusTests();
runCorpusTests();
runMutationTests();
runFuzzTests();
runProtectedCorpusTests();
runRegressionTests();
runMinimalGroundTruthTests();
runL5AuthenticityNegativeTests();
runRound2AuthenticityTests();
runRound3AuditTests();
runSandboxTests();
runCliTests();
runAdmissionGateMatrixTests();
runWorkerProtocolTests();
runQueueTests();
runGatewayTests();
runPhase2SecurityTests();
runRedisMultiProcessTests();

printSummary();

